@startuml

start
:GET /api/flashcards/{flashcard}/current-session
Get session id for flashcards set;

if (Session not exists) then (yes)
    : POST /api/flashcards/{flashcard}/sessions
      Create session for flashcard;
    if (Session not created successfully) then (yes)
        :Display fail reason;
        end
    endif
endif

:GET /api/flashcards/{flashcard}/sessions/{session}}
Get flashcard session details
;
end

@enduml