global:
  resolve_timeout: 1m

route:
  receiver: "grafana"
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  group_by: ['alertname']

receivers:
  - name: grafana
    webhook_configs:
      - url: "https://webhook.site/e61d12cc-8cb5-4090-a22a-ce219f46becd"
        send_resolved: true
