server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: laravel
    static_configs:
      - targets:
          - localhost
        labels:
          job: laravelLogs
          __path__: /var/laravel/storage/*log

  - job_name: docker
    pipeline_stages:
      - docker: {}
      - labels:
          container_name:
      - template:
          source: output
          template: '[{{ .container_name }}] {{ .message }}'
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/docker/containers/*/*log
