global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 30s

scrape_configs:
  - job_name: node_exporter
    static_configs:
      - targets:
          - node_exporter:9100

  - job_name: php_fpm_exporter
    static_configs:
      - targets:
          - php-fpm-exporter:9253

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - "alert-rules.yml"
