@startuml

actor User

User -> App: Request to route with authentication
App -> App: App bootstraping
App -> AuthMiddleware: Handle request
AuthMiddleware -> FirebaseGuard: Get user from token from request
alt #LightBlue Token valid
    AuthMiddleware <- FirebaseGuard: Return user
    AuthMiddleware -> App: Return user
    App -> ApiController: Handle route
    ApiController -> User: Return json response
else #Red Token invalid
    AuthMiddleware <- FirebaseGuard: Return null
    AuthMiddleware -> App: User unauthorized
    App -> User: Unauthenticated response
end

@enduml