@startuml

header Login process
title Login object communication example sequence diagram

participant User
database Postgres order 300

User -> LoginService: Provide credentials
LoginService -> IUserService: Validate user credentials
IUserService -> Postgres: Find user by credentials
Postgres -> IUserService: Return user with credentials or nothing
alt#Gold #LightBlue Credentials valid
    LoginService <- IUserService: Return user
    LoginService -> TokenService: Token request
    TokenService -> Postgres: Store token
    TokenService -> LoginService: Token with TTL response
    LoginService -> User: Return user data with token
else #Red Credentials invalid
    LoginService <- IUserService: Return null
    LoginService -> User: Return invalid credentials response
end

@enduml