name: ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ci:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./entry
    container:
      image: mjakubowski99/words_app
      options: --user 1001
    steps:
     - name: Checkout code
       uses: actions/checkout@v4
     - name: Disable xdebug
       run: export XDEBUG_MODE=off
     - name: Copy .env.ci 
       run: cp .env.example .env
     - name: Install dependencies
       run: composer install
     - name: Run cs fixer check
       run: composer php-cs-fixer-ci
     - name: Static analyse
       run: composer phpstan
