name: ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ci:

    runs-on: ubuntu-latest
    container:
      image: mjakubowski99/words_app
      options: --user 1001
    steps:
     - name: Checkout code
       uses: actions/checkout@v4
     - name: Check current dir
       run: ls
     - name: Disable XDEBUG
       run: export XDEBUG_MODE=off
     - name: Entery entry dir
       run: cd entry
     - name: Copy .env.example
       run: cp .env.example .env
     - name: Install dependencies
       run: composer install 
     - name: Run cs fixer
       run: composer php-cs-fixer-ci
