name: ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ci:

    runs-on: ubuntu-latest
    container:
      image: mjakubowski99/words_app
      options: --user 1001
    steps:
     - name: Checkout code
       uses: actions/checkout@v4
     - name: Run tests
       working-directory: entry
       run: |
        export XDEBUG_MODE=off
        cp .env.example .env
        composer install
        composer php-cs-fixer-ci
