name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Build the app Docker image
          run: docker build -t mjakubowski99/words_app --build-arg USER=app --build-arg UID=1000 --build-arg GID=1000 entry/docker/config/php
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        - name: Push to registery
          run: docker push mjakubowski99/words_app
